# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: "BC Kahiki"
  inputs:
    command: 'build'
    Dockerfile: 'php-apache-Dockerfile'
- task: Docker@2
  displayName: "Gadhi kahi ki"
  inputs:
    containerRegistry: 'acrconnection'
    repository: 'mwimg'
    command: 'push'