# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: "Docker Build"
  inputs:
    containerRegistry: 'acrconnection'
    repository: 'mwimg'
    command: 'build'
    Dockerfile: 'php-apache-Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
- task: Docker@2
  displayName: "Docker Push"
  inputs:
    containerRegistry: 'acrconnection'
    repository: 'mwimg'
    command: 'push'
    tags: |
      $(Build.BuildId)
      latest

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'cicdtest'
    azureResourceGroup: 'aks-cluster-rg'
    kubernetesCluster: 'aks-cluster'
    namespace: 'default'
    manifests: 'deployment.yaml'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'cicdtest'
    azureResourceGroup: 'aks-cluster-rg'
    kubernetesCluster: 'aks-cluster'
    namespace: 'default'
    manifests: 'mysql-deployment.yaml'
    containers: 'kubectl create secret generic mysql-secret --from-literal=MYSQL_ROOT_PASSWORD=root --from-literal=MYSQL_DATABASE=mwdb --from-literal=MYSQL_USER=mwdbadmin --from-literal=MYSQL_PASSWORD=Passw0rd@123'